---
name: CI
on:
  push:
    branches: [main]
    tags: [v*]
  pull_request:
    branches: [main]
permissions:
  contents: read
  pull-requests: write
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.17'

    - uses: int128/aqua-action@v1
      with:
        version: v0.7.9 # renovate: depName=suzuki-shunsuke/aqua

    - run: |
        golangci-lint run --out-format checkstyle |
          reviewdog -f=checkstyle \
            -name="golangci-lint" \
            -reporter=github-pr-review \
            -level=warning \
            -fail-on-error=1
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: test
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      run: bash ci/test.sh go-findconfig
